name: jenkins-operator
namespace: ""
platform: "openshift"
image:
  name: epamedp/jenkins-operator
  version: v2.4.0

edp:
  name: "edp"
  dnsWildCard: ""

jenkins:
  deploy: true
  initImage: "busybox"
  image: "epamedp/edp-jenkins"
  version: "2.4.0"
  storageClass: gp2
  volumeCapacity: 10Gi
  libraryPipelinesRepo: "https://github.com/epmd-edp/edp-library-pipelines.git"
  libraryPipelinesVersion: "2.5.0"
  libraryStagesRepo: "https://github.com/epmd-edp/edp-library-stages.git"
  libraryStagesVersion: "2.5.0"
  pullSecrets:
  basePath: