{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-{{ .Values.global.edpName }}-cluster-role
rules:
- apiGroups:
    - "*"
  attributeRestrictions: null
  resources:
    - podsecuritypolicies
  verbs:
    - get
    - list
    - update
- apiGroups:
    - "*"
  attributeRestrictions: null
  resources:
    - namespaces
  verbs:
    - create
    - get
{{ end }}
