{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edp-{{ .Values.name }}-role-{{ .Values.global.edpName }}
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - adminconsoles
  - cdpipelines
  - codebasebranches
  - codebaseimagestreams
  - codebases
  - edpcomponents
  - gitservers
  - jenkins
  - jenkinses
  - keycloakrealms
  - stages
  - jirafixversions
  verbs:
  - create
  - get
  - list
  - patch
  - update
{{ end}}