{{ if eq .Values.platform "kubernetes" }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  rules:
    - host: {{if .Values.jenkins.basePath}}{{ .Values.edp.dnsWildCard }}{{else}}jenkins-{{ .Values.namespace }}.{{ .Values.edp.dnsWildCard }}{{end}}
      http:
        paths:
          - path: {{if .Values.jenkins.basePath}}/{{.Values.jenkins.basePath}}(/|$)(.*){{else}}/{{end}}
            backend:
              serviceName: jenkins
              servicePort: 8080
status:
  loadBalancer:
    ingress:
{{ end }}