apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-edp-resources-permissions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edp-jenkins-role
subjects:
  - kind: ServiceAccount
    name: jenkins